// DTOLocation \\

export class LocationDTO {
  ParentCode: any;
  ProvinceCode: any;
  DistrictCode: any;
  WardCode: any;
  StatusName: string;
  ListChild: LocationDTO[] | null;
  Code: number;
  ParentID: number | null;
  LocationID: string;
  LocationName: string;
  Brieft: any;
  Address: any;
  Province: any;
  District: any;
  Ward: any;
  Remark: any;
  StatusID: number;
}

export class ListLocationDTO {
  StatusCode?: number = null;
  ErrorString?: string = null;
  ObjectReturn: LocationDTO[];
}

export const ListLocationTree = {
  StatusCode: 0,
  ErrorString: null,
  ObjectReturn: [
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: [
        {
          ParentCode: null,
          ProvinceCode: null,
          DistrictCode: null,
          WardCode: null,
          StatusName: 'Duyệt áp dụng',
          ListChild: [
            {
              ParentCode: null,
              ProvinceCode: null,
              DistrictCode: null,
              WardCode: null,
              StatusName: 'Duyệt áp dụng',
              ListChild: null,
              Code: 3,
              ParentID: 2,
              LocationID: 'DP42',
              LocationName: 'Kho 42',
              Brieft: null,
              Address: null,
              Province: null,
              District: null,
              Ward: null,
              Remark: null,
              StatusID: 2,
            },
          ],
          Code: 2,
          ParentID: 1,
          LocationID: 'LO42',
          LocationName: 'Văn phòng 42',
          Brieft: null,
          Address: null,
          Province: null,
          District: null,
          Ward: null,
          Remark: null,
          StatusID: 2,
        },
      ],
      Code: 1,
      ParentID: null,
      LocationID: 'HW40',
      LocationName: 'Văn phòng 40',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: [
        {
          ParentCode: null,
          ProvinceCode: null,
          DistrictCode: null,
          WardCode: null,
          StatusName: 'Duyệt áp dụng',
          ListChild: [
            {
              ParentCode: null,
              ProvinceCode: null,
              DistrictCode: null,
              WardCode: null,
              StatusName: 'Duyệt áp dụng',
              ListChild: null,
              Code: 25,
              ParentID: 24,
              LocationID: 'DP42',
              LocationName: 'Kho 42',
              Brieft: null,
              Address: null,
              Province: null,
              District: null,
              Ward: null,
              Remark: null,
              StatusID: 2,
            },
          ],
          Code: 24,
          ParentID: 4,
          LocationID: 'LO42',
          LocationName: 'Văn phòng 42',
          Brieft: null,
          Address: null,
          Province: null,
          District: null,
          Ward: null,
          Remark: null,
          StatusID: 2,
        },
      ],
      Code: 4,
      ParentID: null,
      LocationID: 'OW40',
      LocationName: 'Kho Online',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 5,
      ParentID: null,
      LocationID: 'HC01',
      LocationName: 'Hachi Hachi NVT',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 6,
      ParentID: null,
      LocationID: 'HC02',
      LocationName: 'Hachi Hachi PMH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 7,
      ParentID: null,
      LocationID: 'HC03',
      LocationName: 'Hachi Hachi CMT8',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 8,
      ParentID: null,
      LocationID: 'HC04',
      LocationName: 'Hachi Hachi PT',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 9,
      ParentID: null,
      LocationID: 'HC05',
      LocationName: 'Hachi Hachi QT',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 10,
      ParentID: null,
      LocationID: 'HC06',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },

    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 11,
      ParentID: null,
      LocationID: 'HC07',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 12,
      ParentID: null,
      LocationID: 'HC08',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 13,
      ParentID: null,
      LocationID: 'HC09',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },

    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 14,
      ParentID: null,
      LocationID: 'HC10',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 15,
      ParentID: null,
      LocationID: 'HC11',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 16,
      ParentID: null,
      LocationID: 'HC12',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 17,
      ParentID: null,
      LocationID: 'HC13',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 18,
      ParentID: null,
      LocationID: 'HC14',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 19,
      ParentID: null,
      LocationID: 'HC15',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 20,
      ParentID: null,
      LocationID: 'HC16',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 21,
      ParentID: null,
      LocationID: 'HC17',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 22,
      ParentID: null,
      LocationID: 'HC18',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 23,
      ParentID: null,
      LocationID: 'HC19',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
  ],
};

// -------------------------------- \\

// DtoOrg-structure \\

export class DepartmentDTO {
  StatusCode: number;
  ErrorString: string;
  ObjectReturn: ObjectReturn[];
}

export class ObjectReturn {
  StatusName: string;
  ParentCode: any;
  ListLocationCode: any;
  ListLocation: any[];
  ListDepartment: ListDepartment[];
  ListPosition: ListPosition[];
  Code: number;
  ParentID: number;
  DepartmentID: string;
  Department: string;
  Brieft: any;
  Phone: any;
  Fax: any;
  Remark: any;
  Config: any;
  TypeData: number;
  OrderBy: any;
  StatusID: number;
}

export class ListDepartment {
  StatusName: string;
  ParentCode: any;
  ListLocationCode: any;
  ListLocation: any[];
  ListDepartment: ListDepartment[];
  ListPosition: ListPosition[];
  Code: number;
  ParentID: number;
  DepartmentID: string;
  Department: string;
  Brieft: any;
  Phone: any;
  Fax: any;
  Remark: any;
  Config: any;
  TypeData: number;
  OrderBy: any;
  StatusID: number;
}

export class ListPosition {
  DepartmentCode: any;
  ReportToCode: any;
  GroupPositionCode: any;
  StatusName: any;
  ListChild: any;
  Code: number;
  PositionID: string;
  Position: string;
  IsLeader: boolean;
  DepartmentID: number;
  ReportTo: any;
  GroupPosition: any;
  Remark: any;
  OrderBy: any;
  ListOfRoles: any;
  Config: any;
  StatusID: number;
}

export const ListDataOrgStructureTree: DepartmentDTO = {
  StatusCode: 0,
  ErrorString: null,
  ObjectReturn: [
    {
      StatusName: 'Duyệt áp dụng',
      ParentCode: null,
      ListLocationCode: null,
      ListLocation: [
        {
          DepartmentName: 'Hội đồng thành viên',
          LocationName: 'Văn phòng 40',
          Code: 1,
          DepartmentID: 1,
          LocationID: 1,
        },
      ],
      ListDepartment: [
        {
          StatusName: 'Duyệt áp dụng',
          ParentCode: null,
          ListLocationCode: null,
          ListLocation: [
            {
              DepartmentName: 'Ban giám đốc',
              LocationName: 'Văn phòng 40',
              Code: 2,
              DepartmentID: 2,
              LocationID: 1,
            },
          ],
          ListDepartment: [
            {
              StatusName: 'Duyệt áp dụng',
              ParentCode: null,
              ListLocationCode: null,
              ListLocation: [],
              ListDepartment: [
                {
                  StatusName: 'Duyệt áp dụng',
                  ParentCode: null,
                  ListLocationCode: null,
                  ListLocation: [
                    {
                      DepartmentName: 'Bán sỉ',
                      LocationName: 'Văn phòng 40',
                      Code: 3,
                      DepartmentID: 4,
                      LocationID: 1,
                    },
                  ],
                  ListDepartment: null,
                  ListPosition: [
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 5,
                      PositionID: 'WSMA',
                      Position: 'Trưởng phòng Kinh doanh sỉ',
                      IsLeader: true,
                      DepartmentID: 4,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      ListChild: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 24,
                      PositionID: 'WSMT',
                      Position: 'Nhân viên kinh doanh kênh MT',
                      IsLeader: false,
                      DepartmentID: 4,
                      ListChild: null,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ListChild: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 25,
                      PositionID: 'WSGT',
                      Position: 'Nhân viên kinh doanh kênh GT',
                      IsLeader: false,
                      DepartmentID: 4,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 26,
                      PositionID: 'WSAD',
                      Position: 'Admin phòng bán sỉ',
                      IsLeader: false,
                      DepartmentID: 4,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                  ],
                  Code: 4,
                  ParentID: 3,
                  DepartmentID: 'WS',
                  Department: 'Bán sỉ',
                  Brieft: null,
                  Phone: null,
                  Fax: null,
                  Remark: null,
                  Config: null,
                  TypeData: 1,
                  OrderBy: null,
                  StatusID: 2,
                },
                {
                  StatusName: 'Duyệt áp dụng',
                  ParentCode: null,
                  ListLocationCode: null,
                  ListLocation: [
                    {
                      DepartmentName: 'CX',
                      LocationName: 'Văn phòng 40',
                      Code: 4,
                      DepartmentID: 5,
                      LocationID: 1,
                    },
                  ],
                  ListDepartment: null,
                  ListPosition: [
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 6,
                      PositionID: 'CXMA',
                      ListChild: null,
                      Position: 'Trưởng phòng CX',
                      IsLeader: true,
                      DepartmentID: 5,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 27,
                      PositionID: 'CXBS',
                      ListChild: null,
                      Position: 'Giám sát hình ảnh cửa hàng',
                      IsLeader: false,
                      DepartmentID: 5,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 28,
                      PositionID: 'CXWA',
                      ListChild: null,
                      Position: 'Web admin',
                      IsLeader: false,
                      DepartmentID: 5,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 29,
                      PositionID: 'CXCS',
                      ListChild: null,
                      Position: 'Nhân viên chăm sóc khách hàng',
                      IsLeader: false,
                      DepartmentID: 5,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                  ],
                  Code: 5,
                  ParentID: 3,
                  DepartmentID: 'CX',
                  Department: 'CX',
                  Brieft: null,
                  Phone: null,
                  Fax: null,
                  Remark: null,
                  Config: null,
                  TypeData: 1,
                  OrderBy: null,
                  StatusID: 2,
                },
                {
                  StatusName: 'Duyệt áp dụng',
                  ParentCode: null,
                  ListLocationCode: null,
                  ListLocation: [
                    {
                      DepartmentName: 'Thương mại điện tử',
                      LocationName: 'Văn phòng 40',
                      Code: 5,
                      DepartmentID: 6,
                      LocationID: 1,
                    },
                  ],
                  ListDepartment: null,
                  ListPosition: [
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 7,
                      PositionID: 'ECMA',
                      Position: 'Trưởng phòng Thương mại Điện tử',
                      IsLeader: true,
                      DepartmentID: 6,
                      ListChild: null,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 30,
                      PositionID: 'ECDE',
                      Position: 'Nhân viên phát triển TMĐT',
                      IsLeader: false,
                      DepartmentID: 6,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      ListChild: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 31,
                      PositionID: 'ECAD',
                      Position: 'Admin phòng TMĐT',
                      IsLeader: false,
                      DepartmentID: 6,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 32,
                      PositionID: 'ECCO',
                      Position: 'Nhân viên tư vấn Online',
                      IsLeader: false,
                      DepartmentID: 6,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 33,
                      PositionID: 'ECCL',
                      ListChild: null,
                      Position: 'Trưởng nhóm tư vấn Online',
                      IsLeader: false,
                      DepartmentID: 6,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                  ],
                  Code: 6,
                  ParentID: 3,
                  DepartmentID: 'EC',
                  Department: 'Thương mại điện tử',
                  Brieft: null,
                  Phone: null,
                  Fax: null,
                  Remark: null,
                  Config: null,
                  TypeData: 1,
                  OrderBy: null,
                  StatusID: 2,
                },
                {
                  StatusName: 'Duyệt áp dụng',
                  ParentCode: null,
                  ListLocationCode: null,
                  ListLocation: [
                    {
                      DepartmentName: 'HR-IT',
                      LocationName: 'Văn phòng 40',
                      Code: 6,
                      DepartmentID: 7,
                      LocationID: 1,
                    },
                  ],
                  ListDepartment: null,
                  ListPosition: [
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 8,
                      PositionID: 'HIMA',
                      Position: 'Trưởng phòng hành chánh nhân sự',
                      IsLeader: true,
                      ListChild: null,
                      DepartmentID: 7,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 34,
                      PositionID: 'HIGH',
                      Position: 'Chuyên viên Hành chính nhân sự',
                      IsLeader: false,
                      DepartmentID: 7,
                      ListChild: null,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 35,
                      PositionID: 'HILD',
                      ListChild: null,
                      Position: 'Chuyên viên L&D-Truyền thông nội bộ',
                      IsLeader: false,
                      DepartmentID: 7,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 36,
                      PositionID: 'HIBP',
                      Position: 'Chuyên viên Đối tác Nhân sự Khối vận hành',
                      IsLeader: false,
                      DepartmentID: 7,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 37,
                      ListChild: null,
                      PositionID: 'HIIS',
                      Position: 'Chuyên viên IT',
                      IsLeader: false,
                      DepartmentID: 7,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                  ],
                  Code: 7,
                  ParentID: 3,
                  DepartmentID: 'HI',
                  Department: 'HR-IT',
                  Brieft: null,
                  Phone: null,
                  Fax: null,
                  Remark: null,
                  Config: null,
                  TypeData: 1,
                  OrderBy: null,
                  StatusID: 2,
                },
                {
                  StatusName: 'Duyệt áp dụng',
                  ParentCode: null,
                  ListLocationCode: null,
                  ListLocation: [
                    {
                      DepartmentName: 'Kế toán',
                      LocationName: 'Văn phòng 40',
                      Code: 7,
                      DepartmentID: 8,
                      LocationID: 1,
                    },
                  ],
                  ListDepartment: null,
                  ListPosition: [
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 9,
                      ListChild: null,
                      PositionID: 'ACCA',
                      Position: 'Kế toán trưởng',
                      IsLeader: true,
                      DepartmentID: 8,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      ListChild: null,
                      StatusName: null,
                      Code: 38,
                      PositionID: 'ACGA',
                      Position: 'Kế toán tổng hợp',
                      IsLeader: false,
                      DepartmentID: 8,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 39,
                      ListChild: null,
                      PositionID: 'ACSA',
                      Position: 'Kế toán cửa hàng',
                      IsLeader: false,
                      DepartmentID: 8,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ListChild: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 40,
                      PositionID: 'ACAD',
                      Position: 'Admin cửa hàng',
                      IsLeader: false,
                      DepartmentID: 8,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                  ],
                  Code: 8,
                  ParentID: 3,
                  DepartmentID: 'AC',
                  Department: 'Kế toán',
                  Brieft: null,
                  Phone: null,
                  Fax: null,
                  Remark: null,
                  Config: null,
                  TypeData: 1,
                  OrderBy: null,
                  StatusID: 2,
                },
                {
                  StatusName: 'Duyệt áp dụng',
                  ParentCode: null,
                  ListLocationCode: null,
                  ListLocation: [
                    {
                      DepartmentName: 'Marketing',
                      LocationName: 'Văn phòng 40',
                      Code: 8,
                      DepartmentID: 9,
                      LocationID: 1,
                    },
                  ],
                  ListDepartment: null,
                  ListPosition: [
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 12,
                      PositionID: 'MKMA',
                      Position: 'Trưởng phòng Marketing',
                      IsLeader: true,
                      DepartmentID: 9,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      ListChild: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 54,
                      PositionID: 'MKVM',
                      Position: 'Phó phòng Marketing',
                      IsLeader: false,
                      DepartmentID: 9,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 55,
                      PositionID: 'MKVL',
                      Position: 'Trưởng nhóm Sáng tạo Hình ảnh',
                      IsLeader: false,
                      DepartmentID: 9,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      ListChild: null,
                      StatusName: null,
                      Code: 56,
                      PositionID: 'MKTE',
                      Position: 'Nhân viên Marketing',
                      IsLeader: false,
                      DepartmentID: 9,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      ListChild: null,
                      StatusName: null,
                      Code: 57,
                      PositionID: 'MKVP',
                      Position: 'Nhân viên sản xuất hình ảnh',
                      IsLeader: false,
                      DepartmentID: 9,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 58,
                      PositionID: 'MKCP',
                      Position: 'Nhân viên Content Marketing',
                      IsLeader: false,
                      DepartmentID: 9,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 59,
                      PositionID: 'MKDI',
                      Position: 'Nhân viên Digital Marketing',
                      IsLeader: false,
                      DepartmentID: 9,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 60,
                      PositionID: 'MKVD',
                      Position: 'Nhân viên Thiết kế',
                      IsLeader: false,
                      DepartmentID: 9,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 61,
                      ListChild: null,
                      PositionID: 'MKAD',
                      Position: 'Nhân viên Marketing Admin',
                      IsLeader: false,
                      DepartmentID: 9,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 62,
                      ListChild: null,
                      PositionID: 'MKVC',
                      Position: 'Nhân viên Visual Content Marketing',
                      IsLeader: false,
                      DepartmentID: 9,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                  ],
                  Code: 9,
                  ParentID: 3,
                  DepartmentID: 'MK',
                  Department: 'Marketing',
                  Brieft: null,
                  Phone: null,
                  Fax: null,
                  Remark: null,
                  Config: null,
                  TypeData: 1,
                  OrderBy: null,
                  StatusID: 2,
                },
                {
                  StatusName: 'Duyệt áp dụng',
                  ParentCode: null,
                  ListLocationCode: null,
                  ListLocation: [
                    {
                      DepartmentName: 'Merchandising',
                      LocationName: 'Văn phòng 40',
                      Code: 9,
                      DepartmentID: 10,
                      LocationID: 1,
                    },
                  ],
                  ListDepartment: null,
                  ListPosition: [
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 13,
                      ListChild: null,
                      PositionID: 'MDMA',
                      Position: 'Trưởng phòng Merchandising',
                      IsLeader: true,
                      DepartmentID: 10,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 63,
                      PositionID: 'MDVM',
                      Position: 'Phó phòng Merchandising',
                      IsLeader: false,
                      DepartmentID: 10,
                      ReportTo: null,
                      GroupPosition: null,
                      ListChild: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 64,
                      PositionID: 'MDID',
                      Position: 'Nhân viên xuất nhập khẩu',
                      IsLeader: false,
                      DepartmentID: 10,
                      ReportTo: null,
                      ListChild: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 65,
                      ListChild: null,
                      PositionID: 'MDME',
                      Position: 'Chuyên viên Merchandising',
                      IsLeader: false,
                      DepartmentID: 10,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 66,
                      PositionID: 'MDPI',
                      Position: 'Chuyên viên Thông tin sản phẩm',
                      IsLeader: false,
                      DepartmentID: 10,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 67,
                      PositionID: 'MDAD',
                      Position: 'Admin Thu mua',
                      IsLeader: false,
                      DepartmentID: 10,
                      ListChild: null,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 68,
                      PositionID: 'MDAM',
                      Position: 'Nhân viên Merchandising kiêm Admin',
                      IsLeader: false,
                      DepartmentID: 10,
                      ListChild: null,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 69,
                      PositionID: 'MDOE',
                      Position: 'Nhân viên thu mua đặt hàng',
                      IsLeader: false,
                      DepartmentID: 10,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      ListChild: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 70,
                      PositionID: 'MDBL',
                      Position: 'Trưởng nhóm Phát triển thương hiệu',
                      IsLeader: false,
                      DepartmentID: 10,
                      ReportTo: null,
                      ListChild: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 71,
                      ListChild: null,
                      PositionID: 'MDBD',
                      Position: 'Nhân viên Digital Marketing',
                      IsLeader: false,
                      DepartmentID: 10,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 72,
                      ListChild: null,
                      PositionID: 'MDBC',
                      Position: 'Nhân viên content Marketing',
                      IsLeader: false,
                      DepartmentID: 10,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                  ],
                  Code: 10,
                  ParentID: 3,
                  DepartmentID: 'MD',
                  Department: 'Merchandising',
                  Brieft: null,
                  Phone: null,
                  Fax: null,
                  Remark: null,
                  Config: null,
                  TypeData: 1,
                  OrderBy: null,
                  StatusID: 2,
                },
              ],
              ListPosition: [],
              Code: 3,
              ParentID: 2,
              DepartmentID: 'HO',
              Department: 'Khối văn phòng',
              Brieft: null,
              Phone: null,
              Fax: null,
              Remark: null,
              Config: null,
              TypeData: 1,
              OrderBy: null,
              StatusID: 2,
            },
            {
              StatusName: 'Duyệt áp dụng',
              ParentCode: null,
              ListLocationCode: null,
              ListLocation: [],
              ListDepartment: [
                {
                  StatusName: 'Duyệt áp dụng',
                  ParentCode: null,
                  ListLocationCode: null,
                  ListLocation: [
                    {
                      DepartmentName: 'Vận hành bán lẻ',
                      LocationName: 'Hachi Hachi NVT',
                      Code: 10,
                      DepartmentID: 12,
                      LocationID: 5,
                    },
                    {
                      DepartmentName: 'Vận hành bán lẻ',
                      LocationName: 'Hachi Hachi PMH',
                      Code: 11,
                      DepartmentID: 12,
                      LocationID: 6,
                    },
                    {
                      DepartmentName: 'Vận hành bán lẻ',
                      LocationName: 'Hachi Hachi CMT8',
                      Code: 12,
                      DepartmentID: 12,
                      LocationID: 7,
                    },
                    {
                      DepartmentName: 'Vận hành bán lẻ',
                      LocationName: 'Hachi Hachi PT',
                      Code: 13,
                      DepartmentID: 12,
                      LocationID: 8,
                    },
                    {
                      DepartmentName: 'Vận hành bán lẻ',
                      LocationName: 'Hachi Hachi QT',
                      Code: 14,
                      DepartmentID: 12,
                      LocationID: 9,
                    },
                    {
                      DepartmentName: 'Vận hành bán lẻ',
                      LocationName: 'Hachi Hachi DXH',
                      Code: 15,
                      DepartmentID: 12,
                      LocationID: 10,
                    },
                  ],
                  ListDepartment: null,
                  ListPosition: [
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 14,
                      PositionID: 'OPSF',
                      Position: 'Giám sát cửa hàng- ngành thực phẩm',
                      IsLeader: false,
                      DepartmentID: 12,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 15,
                      PositionID: 'OPSH',
                      Position: 'Giám sát cửa hàng- ngành gia dụng',
                      IsLeader: false,
                      DepartmentID: 12,
                      ListChild: null,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 16,
                      PositionID: 'OPSW',
                      Position: 'Giám sát cửa hàng- ngành wellness',
                      IsLeader: false,
                      DepartmentID: 12,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      ListChild: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 17,
                      PositionID: 'OPCF',
                      Position: 'Nhân viên tư vấn thực phẩm',
                      IsLeader: false,
                      DepartmentID: 12,
                      ListChild: null,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 18,
                      PositionID: 'OPCH',
                      Position: 'Nhân viên tư vấn gia dụng',
                      IsLeader: false,
                      DepartmentID: 12,
                      ReportTo: null,
                      GroupPosition: null,
                      ListChild: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 19,
                      PositionID: 'OPCW',
                      Position: 'Nhân viên tư vấn wellness',
                      IsLeader: false,
                      DepartmentID: 12,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListChild: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 20,
                      PositionID: 'OPAF',
                      Position: 'Nhân viên bán hàng thực phẩm',
                      IsLeader: false,
                      DepartmentID: 12,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      ListChild: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 21,
                      PositionID: 'OPAH',
                      Position: 'Nhân viên bán hàng gia dụng',
                      IsLeader: false,
                      DepartmentID: 12,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                      ListChild: null,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 22,
                      PositionID: 'OPCC',
                      Position: 'Thu ngân',
                      IsLeader: false,
                      DepartmentID: 12,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      ListChild: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 23,
                      PositionID: 'OPSD',
                      Position: 'Nhân viên giao hàng',
                      IsLeader: false,
                      DepartmentID: 12,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      ListChild: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 2,
                      PositionID: 'OPMA',
                      Position: 'Trưởng phòng Vận hành bán lẻ',
                      IsLeader: true,
                      DepartmentID: 12,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      ListChild: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 3,
                      PositionID: 'OPSM',
                      Position: 'Cửa hàng trưởng',
                      IsLeader: true,
                      DepartmentID: 12,
                      ListChild: null,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                  ],
                  Code: 12,
                  ParentID: 11,
                  DepartmentID: 'OP',
                  Department: 'Vận hành bán lẻ',
                  Brieft: null,
                  Phone: null,
                  Fax: null,
                  Remark: null,
                  Config: null,
                  TypeData: 1,
                  OrderBy: null,
                  StatusID: 2,
                },
              ],
              ListPosition: [],
              Code: 11,
              ParentID: 2,
              DepartmentID: 'POS',
              Department: 'Khối cửa hàng',
              Brieft: null,
              Phone: null,
              Fax: null,
              Remark: null,
              Config: null,
              TypeData: 1,
              OrderBy: null,
              StatusID: 2,
            },
            {
              StatusName: 'Duyệt áp dụng',
              ParentCode: null,
              ListLocationCode: null,
              ListLocation: [],
              ListDepartment: [
                {
                  StatusName: 'Duyệt áp dụng',
                  ParentCode: null,
                  ListLocationCode: null,
                  ListLocation: [
                    {
                      DepartmentName: 'Logistics',
                      LocationName: 'Văn phòng 42',
                      Code: 16,
                      DepartmentID: 14,
                      LocationID: 2,
                    },
                    {
                      DepartmentName: 'Logistics',
                      LocationName: 'Kho 42',
                      Code: 17,
                      DepartmentID: 14,
                      LocationID: 3,
                    },
                    {
                      DepartmentName: 'Logistics',
                      LocationName: 'Kho Online',
                      Code: 18,
                      DepartmentID: 14,
                      LocationID: 4,
                    },
                  ],
                  ListDepartment: null,
                  ListPosition: [
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 11,
                      ListChild: null,
                      PositionID: 'LGMA',
                      Position: 'Trưởng phòng Logistics',
                      IsLeader: true,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 41,
                      PositionID: 'LGDM',
                      Position: 'Phó phòng Logistics',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 42,
                      PositionID: 'LGDL',
                      Position: 'Thủ kho',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 43,
                      PositionID: 'LGDD',
                      Position: 'Phó thủ kho',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 44,
                      PositionID: 'LGFL',
                      Position: 'Phó thủ kho - nhóm thực phẩm',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 45,
                      PositionID: 'LGOL',
                      Position: 'Thủ kho Online',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      ListChild: null,
                      StatusName: null,
                      Code: 46,
                      PositionID: 'LGOA',
                      Position: 'Admin kho Online',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 47,
                      PositionID: 'LGOP',
                      Position: 'Nhân viên soạn hàng Online',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 48,
                      PositionID: 'LGOS',
                      Position: 'Nhân viên quét đối soát Online',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 49,
                      PositionID: 'LGOW',
                      Position: 'Nhân viên đóng và giao hàng',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 50,
                      PositionID: 'LGOC',
                      Position: 'Nhân viên xử lý đơn hàng sàn TMĐT',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      ListChild: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      Code: 51,
                      PositionID: 'LGRC',
                      Position: 'Nhân viên điều phối bán lẻ',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 52,
                      PositionID: 'LGWC',
                      Position: 'Nhân viên điều phối bán sỉ',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                    {
                      DepartmentCode: null,
                      ReportToCode: null,
                      GroupPositionCode: null,
                      StatusName: null,
                      ListChild: null,
                      Code: 53,
                      PositionID: 'LGWE',
                      Position: 'Nhân viên kho',
                      IsLeader: false,
                      DepartmentID: 14,
                      ReportTo: null,
                      GroupPosition: null,
                      Remark: null,
                      OrderBy: null,
                      ListOfRoles: null,
                      Config: null,
                      StatusID: 0,
                    },
                  ],
                  Code: 14,
                  ParentID: 13,
                  DepartmentID: 'LG',
                  Department: 'Logistics',
                  Brieft: null,
                  Phone: null,
                  Fax: null,
                  Remark: null,
                  Config: null,
                  TypeData: 1,
                  OrderBy: null,
                  StatusID: 2,
                },
              ],
              ListPosition: [],
              Code: 13,
              ParentID: 2,
              DepartmentID: 'SP',
              Department: 'Kho vận',
              Brieft: null,
              Phone: null,
              Fax: null,
              Remark: null,
              Config: null,
              TypeData: 1,
              OrderBy: null,
              StatusID: 2,
            },
          ],
          ListPosition: [
            {
              DepartmentCode: null,
              ReportToCode: null,
              GroupPositionCode: null,
              StatusName: null,
              ListChild: null,
              Code: 4,
              PositionID: 'BDVS',
              Position: 'Phó giám đốc phụ trách Kinh doanh',
              IsLeader: false,
              DepartmentID: 2,
              ReportTo: null,
              GroupPosition: null,
              Remark: null,
              OrderBy: null,
              ListOfRoles: null,
              Config: null,
              StatusID: 0,
            },
            {
              DepartmentCode: null,
              ReportToCode: null,
              GroupPositionCode: null,
              StatusName: null,
              ListChild: null,
              Code: 1,
              PositionID: 'BDGD',
              Position: 'Giám đốc',
              IsLeader: true,
              DepartmentID: 2,
              ReportTo: null,
              GroupPosition: null,
              Remark: null,
              OrderBy: null,
              ListOfRoles: null,
              Config: null,
              StatusID: 0,
            },
            {
              DepartmentCode: null,
              ReportToCode: null,
              GroupPositionCode: null,
              StatusName: null,
              ListChild: null,
              Code: 10,
              PositionID: 'BDVM',
              Position: 'Phó giám đốc phụ trách MD và Supply Chain',
              IsLeader: false,
              DepartmentID: 2,
              ReportTo: null,
              GroupPosition: null,
              Remark: null,
              OrderBy: null,
              ListOfRoles: null,
              Config: null,
              StatusID: 0,
            },
          ],
          Code: 2,
          ParentID: 1,
          DepartmentID: 'BD',
          Department: 'Ban giám đốc',
          Brieft: 'BGD',
          Phone: '054612384545',
          Fax: null,
          Remark: null,
          Config: null,
          TypeData: 1,
          OrderBy: null,
          StatusID: 2,
        },
      ],
      ListPosition: [],
      Code: 1,
      ParentID: null,
      DepartmentID: 'BOM',
      Department: 'Hội đồng thành viên',
      Brieft: 'HDTV',
      Phone: '054612384545',
      Fax: null,
      Remark: null,
      Config: null,
      TypeData: 1,
      OrderBy: null,
      StatusID: 2,
    },
  ],
};

export class Address {
  id: string;
  text: string;
  children?: Address[];
}

export const mockAddress: Address[] = [
  {
    id: 'hcm',
    text: 'Thành phố Hồ Chí Minh',
    children: [
      {
        id: 'q7',
        text: 'Quận 7',
        children: [
          {
            id: 'hachi-pmh',
            text: 'CH Hachi Hachi PMH',
            children: [
              {
                id: '173-nguyen-van-troi',
                text: '173 Nguyễn Văn Trỗi, Phú Nhuận',
              },
            ],
          },
        ],
      },
      {
        id: 'q1',
        text: 'Quận 1',
        children: [
          {
            id: 'hachi-bth',
            text: 'CH Hachi Hachi BTH',
            children: [
              {
                id: '81-cach-mang-thang-8',
                text: '81 Cách Mạng Tháng 8, Quận 1',
              },
            ],
          },
        ],
      },
      {
        id: 'q3',
        text: 'Quận 3',
        children: [
          {
            id: 'hachi-pasteur',
            text: 'CH Hachi Hachi Pasteur',
            children: [
              {
                id: '224a-pasteur',
                text: '224A Pasteur, Quận 3',
              },
            ],
          },
        ],
      },
      {
        id: 'qgv',
        text: 'Quận Gò Vấp',
        children: [
          {
            id: 'hachi-quang-trung',
            text: 'CH Hachi Quang Trung',
            children: [
              {
                id: '22-24-quang-trung',
                text: '22-24 Quang Trung, Gò Vấp',
              },
            ],
          },
        ],
      },
      {
        id: 'q9',
        text: 'Quận 9',
        children: [
          {
            id: 'hachi-dxh',
            text: 'CH Hachi Hachi Đỗ Xuân Hợp',
            children: [
              {
                id: '537a-do-xuan-hop',
                text: '537A Đỗ Xuân Hợp, Quận 9',
              },
            ],
          },
        ],
      },
      {
        id: 'pn',
        text: 'Phú Nhuận',
        children: [
          {
            id: 'hachi-nvt',
            text: 'CH Hachi Hachi NVT',
            children: [
              {
                id: '173-nguyen-van-troi',
                text: '173 Nguyễn Văn Trỗi, Phú Nhuận',
              },
            ],
          },
        ],
      },
    ],
  },
];
