// DTOLocation \\
export class LocationDTO {
  ParentCode: any;
  ProvinceCode: any;
  DistrictCode: any;
  WardCode: any;
  StatusName: string;
  ListChild: LocationDTO[] | null;
  Code: number;
  ParentID: number | null;
  LocationID: string;
  LocationName: string;
  Brieft: any;
  Address: any;
  Province: any;
  District: any;
  Ward: any;
  Remark: any;
  StatusID: number;
}

export const ListLocationTree = {
  StatusCode: 0,
  ErrorString: null,
  ObjectReturn: [
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: [
        {
          ParentCode: null,
          ProvinceCode: null,
          DistrictCode: null,
          WardCode: null,
          StatusName: 'Duyệt áp dụng',
          ListChild: [
            {
              ParentCode: null,
              ProvinceCode: null,
              DistrictCode: null,
              WardCode: null,
              StatusName: 'Duyệt áp dụng',
              ListChild: null,
              Code: 3,
              ParentID: 2,
              LocationID: 'DP42',
              LocationName: 'Kho 42',
              Brieft: null,
              Address: null,
              Province: null,
              District: null,
              Ward: null,
              Remark: null,
              StatusID: 2,
            },
          ],
          Code: 2,
          ParentID: 1,
          LocationID: 'LO42',
          LocationName: 'Văn phòng 42',
          Brieft: null,
          Address: null,
          Province: null,
          District: null,
          Ward: null,
          Remark: null,
          StatusID: 2,
        },
      ],
      Code: 1,
      ParentID: null,
      LocationID: 'HW40',
      LocationName: 'Văn phòng 40',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: [
        {
          ParentCode: null,
          ProvinceCode: null,
          DistrictCode: null,
          WardCode: null,
          StatusName: 'Duyệt áp dụng',
          ListChild: [
            {
              ParentCode: null,
              ProvinceCode: null,
              DistrictCode: null,
              WardCode: null,
              StatusName: 'Duyệt áp dụng',
              ListChild: null,
              Code: 25,
              ParentID: 24,
              LocationID: 'DP42',
              LocationName: 'Kho 42',
              Brieft: null,
              Address: null,
              Province: null,
              District: null,
              Ward: null,
              Remark: null,
              StatusID: 2,
            },
          ],
          Code: 24,
          ParentID: 4,
          LocationID: 'LO42',
          LocationName: 'Văn phòng 42',
          Brieft: null,
          Address: null,
          Province: null,
          District: null,
          Ward: null,
          Remark: null,
          StatusID: 2,
        },
      ],
      Code: 4,
      ParentID: null,
      LocationID: 'OW40',
      LocationName: 'Kho Online',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 5,
      ParentID: null,
      LocationID: 'HC01',
      LocationName: 'Hachi Hachi NVT',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 6,
      ParentID: null,
      LocationID: 'HC02',
      LocationName: 'Hachi Hachi PMH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 7,
      ParentID: null,
      LocationID: 'HC03',
      LocationName: 'Hachi Hachi CMT8',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 8,
      ParentID: null,
      LocationID: 'HC04',
      LocationName: 'Hachi Hachi PT',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 9,
      ParentID: null,
      LocationID: 'HC05',
      LocationName: 'Hachi Hachi QT',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 10,
      ParentID: null,
      LocationID: 'HC06',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },

    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 11,
      ParentID: null,
      LocationID: 'HC07',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 12,
      ParentID: null,
      LocationID: 'HC08',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 13,
      ParentID: null,
      LocationID: 'HC09',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },

    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 14,
      ParentID: null,
      LocationID: 'HC10',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 15,
      ParentID: null,
      LocationID: 'HC11',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 16,
      ParentID: null,
      LocationID: 'HC12',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 17,
      ParentID: null,
      LocationID: 'HC13',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 18,
      ParentID: null,
      LocationID: 'HC14',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 19,
      ParentID: null,
      LocationID: 'HC15',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 20,
      ParentID: null,
      LocationID: 'HC16',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 21,
      ParentID: null,
      LocationID: 'HC17',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 22,
      ParentID: null,
      LocationID: 'HC18',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
    {
      ParentCode: null,
      ProvinceCode: null,
      DistrictCode: null,
      WardCode: null,
      StatusName: 'Duyệt áp dụng',
      ListChild: null,
      Code: 23,
      ParentID: null,
      LocationID: 'HC19',
      LocationName: 'Hachi Hachi DXH',
      Brieft: null,
      Address: null,
      Province: null,
      District: null,
      Ward: null,
      Remark: null,
      StatusID: 2,
    },
  ],
};

// DTOOrg-structure \\

export class DTOStructure {
  id: number = 0;
  name: string = '';
  code: string = '';
  leaderUnit?: boolean = false;
  Abbreviation?: string = '';
  phone?: number = 0;
  task?: string = '';
  location?: string = '';
  SubsidiaryUnit?: string = '';
  fax?: string = '';
  statusCode?: number = 0;
  type: 'unit' | 'position';
  contents?: DTOStructure[];
}

let counter = 0;
const autoId = () => counter++;

export const structure: DTOStructure[] = [
  {
    id: autoId(),
    name: 'Hội đồng quản trị',
    code: 'BoM',
    type: 'unit',
    contents: [
      {
        id: autoId(),
        name: 'Chủ tịch hội đồng quản trị',
        code: 'CD01',
        type: 'position',
      },
      {
        id: autoId(),
        name: 'Ban giám đốc',
        code: 'BoD',
        type: 'unit',
        contents: [
          {
            id: autoId(),
            name: 'Giám đốc',
            code: 'CD02',
            leaderUnit: true,
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc kinh doanh',
            code: 'CD03',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc nội chính',
            code: 'CD04',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Khối văn phòng',
            code: 'HO',
            type: 'unit',
            contents: [
              { id: autoId(), name: 'Phòng thu mua', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng LGT', code: 'PM', type: 'unit' },
              {
                id: autoId(),
                name: 'Phòng Marketing',
                code: 'PM',
                type: 'unit',
              },
              { id: autoId(), name: 'Phòng Nhân sự', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng Kế toán', code: 'PM', type: 'unit' },
            ],
          },
          {
            id: autoId(),
            name: 'Khối cửa hàng',
            code: 'OP',
            type: 'unit',
            contents: [
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 1',
                code: 'OP01',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 2',
                code: 'OP02',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 3',
                code: 'OP03',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 4',
                code: 'OP04',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 5',
                code: 'OP05',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 6',
                code: 'OP06',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 7',
                code: 'OP07',
                type: 'unit',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: autoId(),
    name: 'Hội đồng quản trị',
    code: 'BoM',
    type: 'unit',
    contents: [
      {
        id: autoId(),
        name: 'Chủ tịch hội đồng quản trị',
        code: 'CD01',
        type: 'position',
      },
      {
        id: autoId(),
        name: 'Ban giám đốc',
        code: 'BoD',
        type: 'unit',
        contents: [
          {
            id: autoId(),
            name: 'Giám đốc',
            code: 'CD02',
            leaderUnit: true,
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc kinh doanh',
            code: 'CD03',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc nội chính',
            code: 'CD04',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Khối văn phòng',
            code: 'HO',
            type: 'unit',
            contents: [
              { id: autoId(), name: 'Phòng thu mua', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng LGT', code: 'PM', type: 'unit' },
              {
                id: autoId(),
                name: 'Phòng Marketing',
                code: 'PM',
                type: 'unit',
              },
              { id: autoId(), name: 'Phòng Nhân sự', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng Kế toán', code: 'PM', type: 'unit' },
            ],
          },
          {
            id: autoId(),
            name: 'Khối cửa hàng',
            code: 'OP',
            type: 'unit',
            contents: [
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 1',
                code: 'OP01',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 2',
                code: 'OP02',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 3',
                code: 'OP03',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 4',
                code: 'OP04',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 5',
                code: 'OP05',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 6',
                code: 'OP06',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 7',
                code: 'OP07',
                type: 'unit',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: autoId(),
    name: 'Hội đồng quản trị',
    code: 'BoM',
    type: 'unit',
    contents: [
      {
        id: autoId(),
        name: 'Chủ tịch hội đồng quản trị',
        code: 'CD01',
        type: 'position',
      },
      {
        id: autoId(),
        name: 'Ban giám đốc',
        code: 'BoD',
        type: 'unit',
        contents: [
          {
            id: autoId(),
            name: 'Giám đốc',
            code: 'CD02',
            leaderUnit: true,
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc kinh doanh',
            code: 'CD03',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc nội chính',
            code: 'CD04',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Khối văn phòng',
            code: 'HO',
            type: 'unit',
            contents: [
              { id: autoId(), name: 'Phòng thu mua', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng LGT', code: 'PM', type: 'unit' },
              {
                id: autoId(),
                name: 'Phòng Marketing',
                code: 'PM',
                type: 'unit',
              },
              { id: autoId(), name: 'Phòng Nhân sự', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng Kế toán', code: 'PM', type: 'unit' },
            ],
          },
          {
            id: autoId(),
            name: 'Khối cửa hàng',
            code: 'OP',
            type: 'unit',
            contents: [
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 1',
                code: 'OP01',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 2',
                code: 'OP02',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 3',
                code: 'OP03',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 4',
                code: 'OP04',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 5',
                code: 'OP05',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 6',
                code: 'OP06',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 7',
                code: 'OP07',
                type: 'unit',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: autoId(),
    name: 'Hội đồng quản trị',
    code: 'BoM',
    type: 'unit',
    contents: [
      {
        id: autoId(),
        name: 'Chủ tịch hội đồng quản trị',
        code: 'CD01',
        type: 'position',
      },
      {
        id: autoId(),
        name: 'Ban giám đốc',
        code: 'BoD',
        type: 'unit',
        contents: [
          {
            id: autoId(),
            name: 'Giám đốc',
            code: 'CD02',
            leaderUnit: true,
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc kinh doanh',
            code: 'CD03',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc nội chính',
            code: 'CD04',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Khối văn phòng',
            code: 'HO',
            type: 'unit',
            contents: [
              { id: autoId(), name: 'Phòng thu mua', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng LGT', code: 'PM', type: 'unit' },
              {
                id: autoId(),
                name: 'Phòng Marketing',
                code: 'PM',
                type: 'unit',
              },
              { id: autoId(), name: 'Phòng Nhân sự', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng Kế toán', code: 'PM', type: 'unit' },
            ],
          },
          {
            id: autoId(),
            name: 'Khối cửa hàng',
            code: 'OP',
            type: 'unit',
            contents: [
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 1',
                code: 'OP01',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 2',
                code: 'OP02',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 3',
                code: 'OP03',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 4',
                code: 'OP04',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 5',
                code: 'OP05',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 6',
                code: 'OP06',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 7',
                code: 'OP07',
                type: 'unit',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: autoId(),
    name: 'Hội đồng quản trị',
    code: 'BoM',
    type: 'unit',
    contents: [
      {
        id: autoId(),
        name: 'Chủ tịch hội đồng quản trị',
        code: 'CD01',
        type: 'position',
      },
      {
        id: autoId(),
        name: 'Ban giám đốc',
        code: 'BoD',
        type: 'unit',
        contents: [
          {
            id: autoId(),
            name: 'Giám đốc',
            code: 'CD02',
            leaderUnit: true,
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc kinh doanh',
            code: 'CD03',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc nội chính',
            code: 'CD04',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Khối văn phòng',
            code: 'HO',
            type: 'unit',
            contents: [
              { id: autoId(), name: 'Phòng thu mua', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng LGT', code: 'PM', type: 'unit' },
              {
                id: autoId(),
                name: 'Phòng Marketing',
                code: 'PM',
                type: 'unit',
              },
              { id: autoId(), name: 'Phòng Nhân sự', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng Kế toán', code: 'PM', type: 'unit' },
            ],
          },
          {
            id: autoId(),
            name: 'Khối cửa hàng',
            code: 'OP',
            type: 'unit',
            contents: [
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 1',
                code: 'OP01',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 2',
                code: 'OP02',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 3',
                code: 'OP03',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 4',
                code: 'OP04',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 5',
                code: 'OP05',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 6',
                code: 'OP06',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 7',
                code: 'OP07',
                type: 'unit',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: autoId(),
    name: 'Hội đồng quản trị',
    code: 'BoM',
    type: 'unit',
    contents: [
      {
        id: autoId(),
        name: 'Chủ tịch hội đồng quản trị',
        code: 'CD01',
        type: 'position',
      },
      {
        id: autoId(),
        name: 'Ban giám đốc',
        code: 'BoD',
        type: 'unit',
        contents: [
          {
            id: autoId(),
            name: 'Giám đốc',
            code: 'CD02',
            leaderUnit: true,
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc kinh doanh',
            code: 'CD03',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc nội chính',
            code: 'CD04',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Khối văn phòng',
            code: 'HO',
            type: 'unit',
            contents: [
              { id: autoId(), name: 'Phòng thu mua', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng LGT', code: 'PM', type: 'unit' },
              {
                id: autoId(),
                name: 'Phòng Marketing',
                code: 'PM',
                type: 'unit',
              },
              { id: autoId(), name: 'Phòng Nhân sự', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng Kế toán', code: 'PM', type: 'unit' },
            ],
          },
          {
            id: autoId(),
            name: 'Khối cửa hàng',
            code: 'OP',
            type: 'unit',
            contents: [
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 1',
                code: 'OP01',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 2',
                code: 'OP02',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 3',
                code: 'OP03',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 4',
                code: 'OP04',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 5',
                code: 'OP05',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 6',
                code: 'OP06',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 7',
                code: 'OP07',
                type: 'unit',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: autoId(),
    name: 'Hội đồng quản trị',
    code: 'BoM',
    type: 'unit',
    contents: [
      {
        id: autoId(),
        name: 'Chủ tịch hội đồng quản trị',
        code: 'CD01',
        type: 'position',
      },
      {
        id: autoId(),
        name: 'Ban giám đốc',
        code: 'BoD',
        type: 'unit',
        contents: [
          {
            id: autoId(),
            name: 'Giám đốc',
            code: 'CD02',
            leaderUnit: true,
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc kinh doanh',
            code: 'CD03',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc nội chính',
            code: 'CD04',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Khối văn phòng',
            code: 'HO',
            type: 'unit',
            contents: [
              { id: autoId(), name: 'Phòng thu mua', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng LGT', code: 'PM', type: 'unit' },
              {
                id: autoId(),
                name: 'Phòng Marketing',
                code: 'PM',
                type: 'unit',
              },
              { id: autoId(), name: 'Phòng Nhân sự', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng Kế toán', code: 'PM', type: 'unit' },
            ],
          },
          {
            id: autoId(),
            name: 'Khối cửa hàng',
            code: 'OP',
            type: 'unit',
            contents: [
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 1',
                code: 'OP01',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 2',
                code: 'OP02',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 3',
                code: 'OP03',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 4',
                code: 'OP04',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 5',
                code: 'OP05',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 6',
                code: 'OP06',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 7',
                code: 'OP07',
                type: 'unit',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: autoId(),
    name: 'Hội đồng quản trị',
    code: 'BoM',
    type: 'unit',
    contents: [
      {
        id: autoId(),
        name: 'Chủ tịch hội đồng quản trị',
        code: 'CD01',
        type: 'position',
      },
      {
        id: autoId(),
        name: 'Ban giám đốc',
        code: 'BoD',
        type: 'unit',
        contents: [
          {
            id: autoId(),
            name: 'Giám đốc',
            code: 'CD02',
            leaderUnit: true,
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc kinh doanh',
            code: 'CD03',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc nội chính',
            code: 'CD04',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Khối văn phòng',
            code: 'HO',
            type: 'unit',
            contents: [
              { id: autoId(), name: 'Phòng thu mua', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng LGT', code: 'PM', type: 'unit' },
              {
                id: autoId(),
                name: 'Phòng Marketing',
                code: 'PM',
                type: 'unit',
              },
              { id: autoId(), name: 'Phòng Nhân sự', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng Kế toán', code: 'PM', type: 'unit' },
            ],
          },
          {
            id: autoId(),
            name: 'Khối cửa hàng',
            code: 'OP',
            type: 'unit',
            contents: [
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 1',
                code: 'OP01',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 2',
                code: 'OP02',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 3',
                code: 'OP03',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 4',
                code: 'OP04',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 5',
                code: 'OP05',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 6',
                code: 'OP06',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 7',
                code: 'OP07',
                type: 'unit',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: autoId(),
    name: 'Hội đồng quản trị',
    code: 'BoM',
    type: 'unit',
    contents: [
      {
        id: autoId(),
        name: 'Chủ tịch hội đồng quản trị',
        code: 'CD01',
        type: 'position',
      },
      {
        id: autoId(),
        name: 'Ban giám đốc',
        code: 'BoD',
        type: 'unit',
        contents: [
          {
            id: autoId(),
            name: 'Giám đốc',
            code: 'CD02',
            leaderUnit: true,
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc kinh doanh',
            code: 'CD03',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc nội chính',
            code: 'CD04',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Khối văn phòng',
            code: 'HO',
            type: 'unit',
            contents: [
              { id: autoId(), name: 'Phòng thu mua', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng LGT', code: 'PM', type: 'unit' },
              {
                id: autoId(),
                name: 'Phòng Marketing',
                code: 'PM',
                type: 'unit',
              },
              { id: autoId(), name: 'Phòng Nhân sự', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng Kế toán', code: 'PM', type: 'unit' },
            ],
          },
          {
            id: autoId(),
            name: 'Khối cửa hàng',
            code: 'OP',
            type: 'unit',
            contents: [
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 1',
                code: 'OP01',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 2',
                code: 'OP02',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 3',
                code: 'OP03',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 4',
                code: 'OP04',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 5',
                code: 'OP05',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 6',
                code: 'OP06',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 7',
                code: 'OP07',
                type: 'unit',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: autoId(),
    name: 'Hội đồng quản trị',
    code: 'BoM',
    type: 'unit',
    contents: [
      {
        id: autoId(),
        name: 'Chủ tịch hội đồng quản trị',
        code: 'CD01',
        type: 'position',
      },
      {
        id: autoId(),
        name: 'Ban giám đốc',
        code: 'BoD',
        type: 'unit',
        contents: [
          {
            id: autoId(),
            name: 'Giám đốc',
            code: 'CD02',
            leaderUnit: true,
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc kinh doanh',
            code: 'CD03',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Phó giám đốc nội chính',
            code: 'CD04',
            type: 'position',
          },
          {
            id: autoId(),
            name: 'Khối văn phòng',
            code: 'HO',
            type: 'unit',
            contents: [
              { id: autoId(), name: 'Phòng thu mua', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng LGT', code: 'PM', type: 'unit' },
              {
                id: autoId(),
                name: 'Phòng Marketing',
                code: 'PM',
                type: 'unit',
              },
              { id: autoId(), name: 'Phòng Nhân sự', code: 'PM', type: 'unit' },
              { id: autoId(), name: 'Phòng Kế toán', code: 'PM', type: 'unit' },
            ],
          },
          {
            id: autoId(),
            name: 'Khối cửa hàng',
            code: 'OP',
            type: 'unit',
            contents: [
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 1',
                code: 'OP01',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 2',
                code: 'OP02',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 3',
                code: 'OP03',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 4',
                code: 'OP04',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 5',
                code: 'OP05',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 6',
                code: 'OP06',
                type: 'unit',
              },
              {
                id: autoId(),
                name: 'Cửa hàng Hachi Hachi 7',
                code: 'OP07',
                type: 'unit',
              },
            ],
          },
        ],
      },
    ],
  },
];
